In [2]:
import numpy as np

In [3]:
M = np.array([[1,2,3], [4,5,6], [7,8,9]])
v = np.array([[1],[2],[3]])

In [4]:
print(M.shape)

(3, 3)


In [5]:
#Otra forma de generar matrices
columna1 = [1,2,3]
columna2 = [2,3,4]
columna3 = [5,6,7]
M = np.vstack([columna1,columna2,columna3])

In [6]:
M

array([[1, 2, 3],
       [2, 3, 4],
       [5, 6, 7]])

In [7]:
#Traspuesta
M.T

array([[1, 2, 5],
       [2, 3, 6],
       [3, 4, 7]])

## Producto Punto Revisar

In [8]:
#Inversa Matriz
N = np.linalg.inv(M)

In [9]:
N

array([[-6.75539944e+16,  9.00719925e+16, -2.25179981e+16],
       [ 1.35107989e+17, -1.80143985e+17,  4.50359963e+16],
       [-6.75539944e+16,  9.00719925e+16, -2.25179981e+16]])

In [10]:
#Determinante
N = np.linalg.det(M)
N

4.440892098500594e-17